In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.array(data)
x_data = torch.from_numpy(np_array)
np_array[0] = 100
x_data

tensor([[100, 100],
        [  3,   4]])

In [8]:
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.1726, 0.3778],
        [0.2783, 0.3532]])

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
tensor

tensor([[0.5380, 0.6726, 0.7555, 0.0020],
        [0.7661, 0.1830, 0.9955, 0.2713],
        [0.9520, 0.3606, 0.0066, 0.3820]])

In [17]:
print(torch.cat([tensor, tensor, tensor], dim=1).shape)
torch.cat([tensor, tensor, tensor], dim=1)

torch.Size([3, 12])


tensor([[0.5380, 0.6726, 0.7555, 0.0020, 0.5380, 0.6726, 0.7555, 0.0020, 0.5380,
         0.6726, 0.7555, 0.0020],
        [0.7661, 0.1830, 0.9955, 0.2713, 0.7661, 0.1830, 0.9955, 0.2713, 0.7661,
         0.1830, 0.9955, 0.2713],
        [0.9520, 0.3606, 0.0066, 0.3820, 0.9520, 0.3606, 0.0066, 0.3820, 0.9520,
         0.3606, 0.0066, 0.3820]])

In [20]:
print(tensor.shape)
tensor.sum(dim=0)

torch.Size([3, 4])


tensor([2.2561, 1.2163, 1.7575, 0.6554])

In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
n[0] = 100
print(f"n: {n}")
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
n: [100.   1.   1.   1.   1.]
t: tensor([100.,   1.,   1.,   1.,   1.])
